server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/inventory

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/estoque}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jackson:
    deserialization:
      fail-on-unknown-properties: true

service:
  mock: false

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation